runtime: custom
env: flex
env_variables:
  DATABASE_HOST: ${process.env.DATABASE_HOST}
  DATABASE_USER: ${process.env.DATABASE_USER}
  DATABASE_PASSWORD: ${process.env.DATABASE_PASS}
  DATABASE_NAME: ${process.env.DATABASE_NAME}
beta_settings:
  cloud_sql_instances: pickmysnack:northamerica-northeast1:snack-db=tcp:3306